gold carryover scenarios1
Dugy/Legend_of_the_Invincibles pull request #616
Opened 2023-07-25 15:01 UTC by white-haired-uncle

20230725 10:17:23 warning deprecation: NEW_GOLD_CARRYOVER_NOTE_40 has been deprecated and may be removed in version 1.17.0.; This is now automatically generated and not required. Use [objectives][gold_carryover]carryover_percentage=40 instead.
20230725 10:17:23 warning deprecation: EARLY_FINISH_BONUS_NOTE has been deprecated and may be removed in version 1.17.0.; This is now automatically generated and not required. Use [objectives][gold_carryover]bonus=yes instead.

Breaking up by chapter for easy review.

I'd like to see these in every scenario, instead of assuming player knows the defaults (which could change).

2023-07-25 17:25 UTC, white-haired-uncle commented
Two hundred scenarios, and one comment...

```
#No idea what the hell is this - but it may have some purpose. Was I drunk when
I was writing this?
```

2023-07-25 19:47 UTC, white-haired-uncle commented
Okay, that was a little messy, but part1 is now free of gold carryover messages.

2023-07-25 19:48 UTC, Dugy commented
Can I merge it now?

2023-07-25 20:53 UTC, white-haired-uncle commented
sure

2023-07-25 21:15 UTC, Dugy requested changes

2023-07-25 21:15 UTC, Dugy commented on scenarios2/05_Umbra.cfg
> +                            #textdomain wesnoth-units
Unwanted change.

2023-07-25 21:15 UTC, Dugy commented on scenarios2/05_Umbra.cfg
> +                            #textdomain wesnoth-loti
Unwanted change.

2023-07-25 21:21 UTC, white-haired-uncle commented
Just confirmed it's wmlindent doing that.

2023-07-25 21:23 UTC, white-haired-uncle commented on scenarios2/05_Umbra.cfg
> +                            #textdomain wesnoth-loti
done

2023-07-25 21:23 UTC, white-haired-uncle commented on scenarios2/05_Umbra.cfg
> +                            #textdomain wesnoth-units
done

2023-07-25 23:29 UTC, white-haired-uncle commented
And that's the last of them (not incl spinoffs).

I did notice there are some scenarios in ch10 (at least?) where the gold carry over is only set (to 100) at victory.  I believe this would be misleading if the player assumes that no info in objectives means the wesnoth default.

2023-07-26 08:27 UTC, Dugy commented
> I believe this would be misleading if the player assumes that no info in objectives means the wesnoth default.

Yes, it could be misleading, it does make sense to add carryover notes about that.

2023-07-26 14:16 UTC, white-haired-uncle commented
yes

2023-07-26 14:18 UTC, merged