replace FOREACH in spinoffs
Dugy/Legend_of_the_Invincibles pull request #622
Opened 2023-07-26 23:08 UTC by white-haired-uncle

Looks like wmlindent had a lot to do here.  The only changes I made were to replace the FOREACH loops with for/foreach, and I changed the loop variables in a couple cases that used i for both inner and outer loops (not wrong as I understand it, but IMO it's a lot more readable to just use unique and potentially less error-prone).

I haven't tested any of these.  I'm going to do some other cleanup stuff (have these been brought up to 1.16?  a recent forum comment said no) and then play test.

Ref #621

2023-07-27 19:39 UTC, Dugy commented
Can you please test at least a little of some parts? It's not possible to review it because wmllindent has changed everything.

2023-07-27 20:43 UTC, edwardspec commented on spinoffs/The_Beautiful_Child/utils/utils.cfg
> +#textdomain wesnth-tbc
typo

2023-07-27 20:45 UTC, edwardspec requested changes

2023-07-27 20:45 UTC, edwardspec commented on spinoffs/The_Beautiful_Child/utils/global_events.cfg
> +#textdomain wesnth-tbc
typo

2023-07-27 20:45 UTC, edwardspec commented on spinoffs/The_Beautiful_Child/units/Bringer_of_Light2.cfg
> +main wesnoth-tbc
typo

2023-07-27 20:47 UTC, edwardspec commented
> It's not possible to review it because wmllindent has changed everything.

Can add `?w=1` to the URL of GitHub diff to ignore whitespace changes: https://github.com/Dugy/Legend_of_the_Invincibles/pull/622/files?w=1

2023-07-27 20:51 UTC, Dugy commented
Oh thanks. It looks okay to me. Except for the textdomain issues.

2023-07-27 21:21 UTC, white-haired-uncle commented on spinoffs/The_Beautiful_Child/utils/utils.cfg
> +#textdomain wesnth-tbc
done

2023-07-27 21:22 UTC, white-haired-uncle commented on spinoffs/The_Beautiful_Child/utils/global_events.cfg
> +#textdomain wesnth-tbc
done

2023-07-27 21:22 UTC, white-haired-uncle commented on spinoffs/The_Beautiful_Child/units/Bringer_of_Light2.cfg
> +main wesnoth-tbc
done

2023-07-27 21:40 UTC, edwardspec approved these changes

2023-07-27 21:45 UTC, edwardspec commented on spinoffs/The_Beautiful_Child/utils/utils.cfg
> +#textdomain wesnth-tbc
Still exists.

2023-07-28 00:02 UTC, white-haired-uncle commented
In Kill the King, it always says there's an early finish bonus, but it's 0 per turn.  I think this  is because gold/village and base income are 0.

2023-07-28 00:15 UTC, white-haired-uncle commented
> Can you please test at least a little of some parts? It's not possible to review it because wmllindent has changed everything.

I played all of KtK, not realizing the only foreach was at the very end of the last scenario.  And it was broken ([do] before array=).

2023-07-28 07:05 UTC, merged